// Landrealm Nationwide Seed — 7 Major US Metro Areas
// Run with: npx tsx db/seed-nationwide.ts

import 'dotenv/config';
import { createConnection } from 'mysql2/promise';
import { drizzle } from 'drizzle-orm/mysql2';
import * as schema from './schema';

const dbUrl = process.env.DATABASE_URL;
if (!dbUrl) throw new Error('DATABASE_URL not set');

const client = await createConnection(dbUrl);
const db = drizzle(client);

console.log('Connected to TiDB. Seeding nationwide data...\n');

// ──────────────────────────────────────────
// STEP 1: ZONING RULES — 7 cities × 5 zones each
// ──────────────────────────────────────────

const zoningRulesData = [
  // AUSTIN, TX
  { jurisdiction: "Austin, TX", jurisdictionCode: "AUS-TX", zoneCode: "SF-3", zoneName: "Family Residence", zoneCategory: "Single Family", lotSizeMinSqft: 5750, lotWidthMinFt: 50, frontSetbackFt: 25, rearSetbackFt: 20, sideSetbackFt: 7, maxHeightFt: 35, maxStories: 2, farMax: "0.40", coverageMaxPct: 45, parkingRequired: "2 covered", permittedUses: ["Single-family dwelling","Home occupation"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Corner lots: 10ft side setback. Alley access: 5ft rear setback. Corner visibility triangle required.", source: "City of Austin Land Development Code" },
  { jurisdiction: "Austin, TX", jurisdictionCode: "AUS-TX", zoneCode: "SF-2", zoneName: "Family Residence (Large Lot)", zoneCategory: "Single Family", lotSizeMinSqft: 14000, lotWidthMinFt: 80, frontSetbackFt: 25, rearSetbackFt: 25, sideSetbackFt: 10, maxHeightFt: 35, maxStories: 2, farMax: "0.35", coverageMaxPct: 40, parkingRequired: "2 covered", permittedUses: ["Single-family dwelling","Duplex","Home occupation"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "Min 7,000 sqft per dwelling unit for duplexes.", source: "City of Austin Land Development Code" },
  { jurisdiction: "Austin, TX", jurisdictionCode: "AUS-TX", zoneCode: "MF-1", zoneName: "Multifamily Residence (Limited)", zoneCategory: "Multi Family", lotSizeMinSqft: 8000, lotWidthMinFt: 60, frontSetbackFt: 20, rearSetbackFt: 15, sideSetbackFt: 5, maxHeightFt: 45, maxStories: 3, farMax: "0.80", coverageMaxPct: 60, parkingRequired: "1.5 per unit", permittedUses: ["Duplex","Triplex","Fourplex","Townhouse"], prohibitedUses: ["Commercial retail","Industrial"], specialRequirements: "Max 4 units per structure.", source: "City of Austin Land Development Code" },
  { jurisdiction: "Austin, TX", jurisdictionCode: "AUS-TX", zoneCode: "MF-2", zoneName: "Multifamily Residence", zoneCategory: "Multi Family", lotSizeMinSqft: 12000, lotWidthMinFt: 75, frontSetbackFt: 20, rearSetbackFt: 15, sideSetbackFt: 5, maxHeightFt: 60, maxStories: 4, farMax: "1.50", coverageMaxPct: 70, parkingRequired: "1.25 per unit", permittedUses: ["Multifamily dwelling","Group residential"], prohibitedUses: ["Heavy industrial","Auto salvage"], specialRequirements: "Affordability bonus: +1 story / 0.2 FAR with 10% MFI units.", source: "City of Austin Land Development Code" },
  { jurisdiction: "Austin, TX", jurisdictionCode: "AUS-TX", zoneCode: "CS-1", zoneName: "Commercial (Neighborhood)", zoneCategory: "Commercial", lotSizeMinSqft: 6000, lotWidthMinFt: 50, frontSetbackFt: 0, rearSetbackFt: 10, sideSetbackFt: 0, maxHeightFt: 45, maxStories: 3, farMax: "1.50", coverageMaxPct: 85, parkingRequired: "1 per 300 sqft", permittedUses: ["Retail","Restaurant","Office","Medical"], prohibitedUses: ["Heavy industrial","Outdoor storage"], specialRequirements: "Pedestrian-oriented design required. Ground floor retail encouraged.", source: "City of Austin Land Development Code" },

  // NEW YORK, NY
  { jurisdiction: "New York, NY", jurisdictionCode: "NYC-NY", zoneCode: "R1-1", zoneName: "Single Family Detached", zoneCategory: "Single Family", lotSizeMinSqft: 9250, lotWidthMinFt: 60, frontSetbackFt: 20, rearSetbackFt: 30, sideSetbackFt: 13, maxHeightFt: 35, maxStories: 2, farMax: "0.50", coverageMaxPct: 50, parkingRequired: "1 per dwelling", permittedUses: ["Single-family detached"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Front yard must be at least 20ft deep or half the average of adjoining lots.", source: "NYC Zoning Resolution" },
  { jurisdiction: "New York, NY", jurisdictionCode: "NYC-NY", zoneCode: "R3-1", zoneName: "Small-Scale Multi-Family", zoneCategory: "Multi Family", lotSizeMinSqft: 3200, lotWidthMinFt: 25, frontSetbackFt: 10, rearSetbackFt: 30, sideSetbackFt: 5, maxHeightFt: 33, maxStories: 2, farMax: "0.60", coverageMaxPct: 55, parkingRequired: "0.5 per unit (max 1)", permittedUses: ["Two-family dwelling","Three-family dwelling"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "Parking reduced due to transit access.", source: "NYC Zoning Resolution" },
  { jurisdiction: "New York, NY", jurisdictionCode: "NYC-NY", zoneCode: "R5", zoneName: "Multi-Family Medium Density", zoneCategory: "Multi Family", lotSizeMinSqft: 0, lotWidthMinFt: 0, frontSetbackFt: 10, rearSetbackFt: 30, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 4, farMax: "1.25", coverageMaxPct: 70, parkingRequired: "0.67 per unit", permittedUses: ["Multi-family residential","Community facility"], prohibitedUses: ["Heavy manufacturing","Auto body shop"], specialRequirements: "Inclusionary Housing: 20% affordable = FAR bonus.", source: "NYC Zoning Resolution" },
  { jurisdiction: "New York, NY", jurisdictionCode: "NYC-NY", zoneCode: "C1-3", zoneName: "Local Retail", zoneCategory: "Commercial", lotSizeMinSqft: 0, lotWidthMinFt: 0, frontSetbackFt: 0, rearSetbackFt: 0, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 4, farMax: "2.00", coverageMaxPct: 80, parkingRequired: "1 per 500 sqft", permittedUses: ["Retail","Personal service","Restaurant"], prohibitedUses: ["Heavy manufacturing","Gas station"], specialRequirements: "Residential above commercial required in mixed buildings.", source: "NYC Zoning Resolution" },
  { jurisdiction: "New York, NY", jurisdictionCode: "NYC-NY", zoneCode: "R7-1", zoneName: "Medium Density Apartment", zoneCategory: "Multi Family", lotSizeMinSqft: 0, lotWidthMinFt: 0, frontSetbackFt: 0, rearSetbackFt: 30, sideSetbackFt: 0, maxHeightFt: 75, maxStories: 7, farMax: "3.44", coverageMaxPct: 70, parkingRequired: "0.5 per unit", permittedUses: ["Multi-family residential","Community facility","Nursery"], prohibitedUses: ["Heavy manufacturing"], specialRequirements: "Quality Housing Program applies. Tower-on-a-base required.", source: "NYC Zoning Resolution" },

  // LOS ANGELES, CA
  { jurisdiction: "Los Angeles, CA", jurisdictionCode: "LAX-CA", zoneCode: "R1-1", zoneName: "One Family Residential", zoneCategory: "Single Family", lotSizeMinSqft: 5000, lotWidthMinFt: 50, frontSetbackFt: 20, rearSetbackFt: 15, sideSetbackFt: 5, maxHeightFt: 33, maxStories: 2, farMax: "1.50", coverageMaxPct: 45, parkingRequired: "2 covered", permittedUses: ["Single-family dwelling"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Basement counts toward FAR at 50%.", source: "LA Municipal Code" },
  { jurisdiction: "Los Angeles, CA", jurisdictionCode: "LAX-CA", zoneCode: "R2-1", zoneName: "Two Family Residential", zoneCategory: "Multi Family", lotSizeMinSqft: 5000, lotWidthMinFt: 50, frontSetbackFt: 20, rearSetbackFt: 15, sideSetbackFt: 5, maxHeightFt: 33, maxStories: 2, farMax: "1.50", coverageMaxPct: 45, parkingRequired: "1 per unit", permittedUses: ["Two-family dwelling","Single-family"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "Second unit must be at least 400 sqft.", source: "LA Municipal Code" },
  { jurisdiction: "Los Angeles, CA", jurisdictionCode: "LAX-CA", zoneCode: "R3-1", zoneName: "Multiple Dwelling (Limited)", zoneCategory: "Multi Family", lotSizeMinSqft: 5000, lotWidthMinFt: 50, frontSetbackFt: 15, rearSetbackFt: 10, sideSetbackFt: 5, maxHeightFt: 45, maxStories: 4, farMax: "1.50", coverageMaxPct: 50, parkingRequired: "1 per unit", permittedUses: ["Multi-family dwelling","Boarding house"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "Open space: 100 sqft per unit.", source: "LA Municipal Code" },
  { jurisdiction: "Los Angeles, CA", jurisdictionCode: "LAX-CA", zoneCode: "R4-1", zoneName: "Multiple Dwelling", zoneCategory: "Multi Family", lotSizeMinSqft: 5000, lotWidthMinFt: 50, frontSetbackFt: 15, rearSetbackFt: 10, sideSetbackFt: 5, maxHeightFt: 45, maxStories: 4, farMax: "3.00", coverageMaxPct: 60, parkingRequired: "1 per unit + 0.25 visitors", permittedUses: ["Multi-family dwelling","Elderly housing"], prohibitedUses: ["Heavy industrial","Auto wrecking"], specialRequirements: "Transit Oriented Communities: density bonus near transit.", source: "LA Municipal Code" },
  { jurisdiction: "Los Angeles, CA", jurisdictionCode: "LAX-CA", zoneCode: "C1-1", zoneName: "Limited Commercial", zoneCategory: "Commercial", lotSizeMinSqft: 5000, lotWidthMinFt: 50, frontSetbackFt: 0, rearSetbackFt: 10, sideSetbackFt: 0, maxHeightFt: 45, maxStories: 4, farMax: "1.50", coverageMaxPct: 80, parkingRequired: "1 per 400 sqft", permittedUses: ["Retail","Office","Restaurant"], prohibitedUses: ["Heavy manufacturing","Warehouse"], specialRequirements: "Mixed-use required on designated boulevards.", source: "LA Municipal Code" },

  // CHICAGO, IL
  { jurisdiction: "Chicago, IL", jurisdictionCode: "CHI-IL", zoneCode: "RS-1", zoneName: "Residential Single-Unit", zoneCategory: "Single Family", lotSizeMinSqft: 2500, lotWidthMinFt: 25, frontSetbackFt: 15, rearSetbackFt: 30, sideSetbackFt: 5, maxHeightFt: 30, maxStories: 2, farMax: "1.20", coverageMaxPct: 50, parkingRequired: "1 per unit", permittedUses: ["Single-family dwelling"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Floor area includes basement.", source: "Chicago Zoning Ordinance" },
  { jurisdiction: "Chicago, IL", jurisdictionCode: "CHI-IL", zoneCode: "RS-2", zoneName: "Residential Single-Unit (Detached)", zoneCategory: "Single Family", lotSizeMinSqft: 5000, lotWidthMinFt: 40, frontSetbackFt: 20, rearSetbackFt: 30, sideSetbackFt: 10, maxHeightFt: 30, maxStories: 2, farMax: "1.00", coverageMaxPct: 40, parkingRequired: "2 per unit", permittedUses: ["Single-family detached"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Corner lots: 15ft side setback on street side.", source: "Chicago Zoning Ordinance" },
  { jurisdiction: "Chicago, IL", jurisdictionCode: "CHI-IL", zoneCode: "RT-4", zoneName: "Two-Flat to Four-Flat", zoneCategory: "Multi Family", lotSizeMinSqft: 1650, lotWidthMinFt: 25, frontSetbackFt: 10, rearSetbackFt: 30, sideSetbackFt: 3, maxHeightFt: 38, maxStories: 4, farMax: "1.50", coverageMaxPct: 60, parkingRequired: "0.5 per unit", permittedUses: ["Two-flat","Three-flat","Four-flat"], prohibitedUses: ["Commercial","Heavy industrial"], specialRequirements: "Rear setback measured from alley centerline.", source: "Chicago Zoning Ordinance" },
  { jurisdiction: "Chicago, IL", jurisdictionCode: "CHI-IL", zoneCode: "RM-5", zoneName: "Residential Multi-Unit", zoneCategory: "Multi Family", lotSizeMinSqft: 1650, lotWidthMinFt: 25, frontSetbackFt: 10, rearSetbackFt: 30, sideSetbackFt: 3, maxHeightFt: 55, maxStories: 5, farMax: "2.00", coverageMaxPct: 75, parkingRequired: "0.5 per unit", permittedUses: ["Multi-family dwelling","Group living"], prohibitedUses: ["Heavy industrial","Junk yard"], specialRequirements: "Affordable Housing bonus: up to 2.5 FAR with 20% affordable.", source: "Chicago Zoning Ordinance" },
  { jurisdiction: "Chicago, IL", jurisdictionCode: "CHI-IL", zoneCode: "B1-1", zoneName: "Neighborhood Shopping District", zoneCategory: "Commercial", lotSizeMinSqft: 0, lotWidthMinFt: 25, frontSetbackFt: 0, rearSetbackFt: 0, sideSetbackFt: 0, maxHeightFt: 30, maxStories: 2, farMax: "1.50", coverageMaxPct: 100, parkingRequired: "1 per 500 sqft", permittedUses: ["Retail","Restaurant","Service"], prohibitedUses: ["Heavy manufacturing","Drive-through"], specialRequirements: "Dwelling units permitted above first floor.", source: "Chicago Zoning Ordinance" },

  // HOUSTON, TX
  { jurisdiction: "Houston, TX", jurisdictionCode: "HOU-TX", zoneCode: "R-1", zoneName: "Single Family Residence", zoneCategory: "Single Family", lotSizeMinSqft: 3500, lotWidthMinFt: 35, frontSetbackFt: 25, rearSetbackFt: 10, sideSetbackFt: 3, maxHeightFt: 35, maxStories: 2, farMax: "0.50", coverageMaxPct: 50, parkingRequired: "2 covered", permittedUses: ["Single-family dwelling","Church"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Houston has no traditional zoning; these are Chapter 42 development regulations.", source: "Houston Code of Ordinances, Chapter 42" },
  { jurisdiction: "Houston, TX", jurisdictionCode: "HOU-TX", zoneCode: "R-2", zoneName: "Single Family (Large Lot)", zoneCategory: "Single Family", lotSizeMinSqft: 7500, lotWidthMinFt: 60, frontSetbackFt: 25, rearSetbackFt: 10, sideSetbackFt: 5, maxHeightFt: 35, maxStories: 2, farMax: "0.40", coverageMaxPct: 45, parkingRequired: "2 covered", permittedUses: ["Single-family dwelling","Duplex"], prohibitedUses: ["Commercial"], specialRequirements: "Platting required for new subdivisions.", source: "Houston Code of Ordinances, Chapter 42" },
  { jurisdiction: "Houston, TX", jurisdictionCode: "HOU-TX", zoneCode: "R-3", zoneName: "Two Family", zoneCategory: "Multi Family", lotSizeMinSqft: 4500, lotWidthMinFt: 40, frontSetbackFt: 20, rearSetbackFt: 10, sideSetbackFt: 3, maxHeightFt: 35, maxStories: 2, farMax: "0.75", coverageMaxPct: 55, parkingRequired: "1.5 per unit", permittedUses: ["Two-family dwelling","Duplex"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "Minimum lot area per unit: 2,250 sqft.", source: "Houston Code of Ordinances, Chapter 42" },
  { jurisdiction: "Houston, TX", jurisdictionCode: "HOU-TX", zoneCode: "R-4", zoneName: "Multi-Family", zoneCategory: "Multi Family", lotSizeMinSqft: 3000, lotWidthMinFt: 35, frontSetbackFt: 20, rearSetbackFt: 10, sideSetbackFt: 3, maxHeightFt: 45, maxStories: 4, farMax: "1.25", coverageMaxPct: 65, parkingRequired: "1.25 per unit", permittedUses: ["Multi-family dwelling","Townhouse"], prohibitedUses: ["Heavy industrial"], specialRequirements: "Buffer required adjacent to single-family.", source: "Houston Code of Ordinances, Chapter 42" },
  { jurisdiction: "Houston, TX", jurisdictionCode: "HOU-TX", zoneCode: "C-1", zoneName: "Neighborhood Commercial", zoneCategory: "Commercial", lotSizeMinSqft: 0, lotWidthMinFt: 25, frontSetbackFt: 0, rearSetbackFt: 10, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 3, farMax: "1.50", coverageMaxPct: 85, parkingRequired: "1 per 300 sqft", permittedUses: ["Retail","Office","Restaurant"], prohibitedUses: ["Heavy industrial","Auto salvage"], specialRequirements: "Form-based code applies in certain districts.", source: "Houston Code of Ordinances, Chapter 42" },

  // PHOENIX, AZ
  { jurisdiction: "Phoenix, AZ", jurisdictionCode: "PHX-AZ", zoneCode: "R1-6", zoneName: "Single Family (6,000 sqft)", zoneCategory: "Single Family", lotSizeMinSqft: 6000, lotWidthMinFt: 60, frontSetbackFt: 20, rearSetbackFt: 20, sideSetbackFt: 5, maxHeightFt: 30, maxStories: 2, farMax: "0.50", coverageMaxPct: 50, parkingRequired: "2 covered", permittedUses: ["Single-family dwelling","Guest house"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "Guest house max 1,000 sqft.", source: "Phoenix Zoning Ordinance" },
  { jurisdiction: "Phoenix, AZ", jurisdictionCode: "PHX-AZ", zoneCode: "R1-8", zoneName: "Single Family (8,000 sqft)", zoneCategory: "Single Family", lotSizeMinSqft: 8000, lotWidthMinFt: 70, frontSetbackFt: 25, rearSetbackFt: 20, sideSetbackFt: 7, maxHeightFt: 30, maxStories: 2, farMax: "0.40", coverageMaxPct: 45, parkingRequired: "2 covered + RV", permittedUses: ["Single-family dwelling","Guest house"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "RV parking space required.", source: "Phoenix Zoning Ordinance" },
  { jurisdiction: "Phoenix, AZ", jurisdictionCode: "PHX-AZ", zoneCode: "R-2", zoneName: "Two Family", zoneCategory: "Multi Family", lotSizeMinSqft: 5000, lotWidthMinFt: 50, frontSetbackFt: 20, rearSetbackFt: 15, sideSetbackFt: 5, maxHeightFt: 35, maxStories: 2, farMax: "0.75", coverageMaxPct: 55, parkingRequired: "1.5 per unit", permittedUses: ["Two-family dwelling"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "Open space: 150 sqft per unit.", source: "Phoenix Zoning Ordinance" },
  { jurisdiction: "Phoenix, AZ", jurisdictionCode: "PHX-AZ", zoneCode: "R-3", zoneName: "Multi-Family", zoneCategory: "Multi Family", lotSizeMinSqft: 4000, lotWidthMinFt: 40, frontSetbackFt: 15, rearSetbackFt: 10, sideSetbackFt: 5, maxHeightFt: 45, maxStories: 4, farMax: "1.50", coverageMaxPct: 65, parkingRequired: "1.25 per unit", permittedUses: ["Multi-family dwelling","Townhouse"], prohibitedUses: ["Heavy industrial"], specialRequirements: "Xeriscape required for all landscaping.", source: "Phoenix Zoning Ordinance" },
  { jurisdiction: "Phoenix, AZ", jurisdictionCode: "PHX-AZ", zoneCode: "C-1", zoneName: "Neighborhood Commercial", zoneCategory: "Commercial", lotSizeMinSqft: 0, lotWidthMinFt: 40, frontSetbackFt: 0, rearSetbackFt: 10, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 3, farMax: "1.50", coverageMaxPct: 80, parkingRequired: "1 per 300 sqft", permittedUses: ["Retail","Office","Restaurant"], prohibitedUses: ["Heavy industrial","Outdoor storage"], specialRequirements: "Shade structures required for parking.", source: "Phoenix Zoning Ordinance" },

  // SAN FRANCISCO, CA
  { jurisdiction: "San Francisco, CA", jurisdictionCode: "SFO-CA", zoneCode: "RH-1", zoneName: "Residential House, One Family", zoneCategory: "Single Family", lotSizeMinSqft: 2500, lotWidthMinFt: 25, frontSetbackFt: 0, rearSetbackFt: 45, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 3, farMax: "1.80", coverageMaxPct: 100, parkingRequired: "1 per unit", permittedUses: ["Single-family dwelling"], prohibitedUses: ["Multi-family","Commercial"], specialRequirements: "No front setback required. Rear yard: 45% of lot depth.", source: "San Francisco Planning Code" },
  { jurisdiction: "San Francisco, CA", jurisdictionCode: "SFO-CA", zoneCode: "RH-2", zoneName: "Residential House, Two Family", zoneCategory: "Multi Family", lotSizeMinSqft: 2500, lotWidthMinFt: 25, frontSetbackFt: 0, rearSetbackFt: 45, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 3, farMax: "1.80", coverageMaxPct: 100, parkingRequired: "1 per unit", permittedUses: ["Two-family dwelling"], prohibitedUses: ["Commercial","Industrial"], specialRequirements: "No front setback. Rear yard: 45% of lot depth.", source: "San Francisco Planning Code" },
  { jurisdiction: "San Francisco, CA", jurisdictionCode: "SFO-CA", zoneCode: "RM-1", zoneName: "Residential Mixed, Low Density", zoneCategory: "Multi Family", lotSizeMinSqft: 2500, lotWidthMinFt: 25, frontSetbackFt: 0, rearSetbackFt: 45, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 3, farMax: "2.00", coverageMaxPct: 100, parkingRequired: "1 per unit", permittedUses: ["Multi-family dwelling","Group housing"], prohibitedUses: ["Heavy industrial"], specialRequirements: "No front setback. Rear yard: 45% of lot depth.", source: "San Francisco Planning Code" },
  { jurisdiction: "San Francisco, CA", jurisdictionCode: "SFO-CA", zoneCode: "RM-2", zoneName: "Residential Mixed, Medium Density", zoneCategory: "Multi Family", lotSizeMinSqft: 1500, lotWidthMinFt: 0, frontSetbackFt: 0, rearSetbackFt: 45, sideSetbackFt: 0, maxHeightFt: 65, maxStories: 5, farMax: "3.00", coverageMaxPct: 100, parkingRequired: "0.5 per unit", permittedUses: ["Multi-family dwelling","Senior housing"], prohibitedUses: ["Heavy industrial"], specialRequirements: "Neighborhood notification required. Parking can be reduced near transit.", source: "San Francisco Planning Code" },
  { jurisdiction: "San Francisco, CA", jurisdictionCode: "SFO-CA", zoneCode: "NC-1", zoneName: "Neighborhood Commercial, Small Scale", zoneCategory: "Commercial", lotSizeMinSqft: 0, lotWidthMinFt: 0, frontSetbackFt: 0, rearSetbackFt: 0, sideSetbackFt: 0, maxHeightFt: 40, maxStories: 3, farMax: "2.00", coverageMaxPct: 100, parkingRequired: "1 per 500 sqft", permittedUses: ["Retail","Restaurant","Office","Residential above"], prohibitedUses: ["Heavy manufacturing","Auto repair"], specialRequirements: "Residential uses encouraged above ground floor.", source: "San Francisco Planning Code" },
];

console.log(`Inserting ${zoningRulesData.length} zoning rules...`);
await db.insert(schema.zoningRules).values(zoningRulesData);
console.log(`  Zoning rules inserted.\n`);

// ──────────────────────────────────────────
// STEP 2: CONTRACTORS — 5 per city × 7 cities
// ──────────────────────────────────────────

const contractorData = [
  // AUSTIN
  { name: "Austin Pro Builders", specialty: "General Contractor", licenseNumber: "TX-AUS-12345", licenseState: "TX", rating: "4.80", reviewCount: 142, yearsExperience: 15, projectsCompleted: 320, phone: "(512) 555-0101", email: "info@austinprobuilders.com", city: "Austin", state: "TX", bio: "Full-service general contractor specializing in residential and commercial construction in the Austin metro area.", services: ["New Construction","Renovations","ADUs"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Hill Country Electric", specialty: "Electrical", licenseNumber: "TX-AUS-23456", licenseState: "TX", rating: "4.70", reviewCount: 89, yearsExperience: 12, projectsCompleted: 210, phone: "(512) 555-0102", email: "service@hillcountryelectric.com", city: "Austin", state: "TX", bio: "Licensed electrical contractor serving Austin and surrounding areas.", services: ["Residential Wiring","Service Upgrades","EV Charging"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "ATX Plumbing Pros", specialty: "Plumbing", licenseNumber: "TX-AUS-34567", licenseState: "TX", rating: "4.60", reviewCount: 156, yearsExperience: 10, projectsCompleted: 180, phone: "(512) 555-0103", email: "jobs@atxplumbing.com", city: "Austin", state: "TX", bio: "Full-service plumbing contractor for new construction and remodels.", services: ["New Construction Plumbing","Water Heaters","Repiping"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Capitol City HVAC", specialty: "HVAC", licenseNumber: "TX-AUS-45678", licenseState: "TX", rating: "4.50", reviewCount: 67, yearsExperience: 8, projectsCompleted: 95, phone: "(512) 555-0104", email: "schedule@capitolhvac.com", city: "Austin", state: "TX", bio: "HVAC design, installation, and service for residential new construction.", services: ["System Design","Installation","Ductwork"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Austin Structural Engineers", specialty: "Structural Engineering", licenseNumber: "TX-AUS-56789", licenseState: "TX", rating: "4.90", reviewCount: 43, yearsExperience: 20, projectsCompleted: 150, phone: "(512) 555-0105", email: "projects@austinstruc.com", city: "Austin", state: "TX", bio: "Structural engineering for residential, commercial, and multi-family projects.", services: ["Structural Analysis","Foundation Design","Seismic"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TBPE.texas.gov." },
  // NEW YORK
  { name: "Manhattan Build Corp", specialty: "General Contractor", licenseNumber: "NYC-12345", licenseState: "NY", rating: "4.90", reviewCount: 210, yearsExperience: 22, projectsCompleted: 450, phone: "(212) 555-0201", email: "info@manhattanbuild.com", city: "New York", state: "NY", bio: "High-end residential and commercial construction in NYC boroughs.", services: ["Renovations","New Construction","Landmarked Buildings"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at NYC.gov/buildings." },
  { name: "Brooklyn Renos LLC", specialty: "Renovation", licenseNumber: "NYC-23456", licenseState: "NY", rating: "4.70", reviewCount: 178, yearsExperience: 16, projectsCompleted: 310, phone: "(718) 555-0202", email: "hello@brooklynrenos.com", city: "New York", state: "NY", bio: "Brownstone and townhouse renovations throughout Brooklyn.", services: ["Brownstone Reno","Townhouse Gut","Extensions"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at NYC.gov/buildings." },
  { name: "NYC Structural Group", specialty: "Structural Engineering", licenseNumber: "NY-SE-34567", licenseState: "NY", rating: "4.80", reviewCount: 92, yearsExperience: 25, projectsCompleted: 280, phone: "(212) 555-0203", email: "projects@nycstructural.com", city: "New York", state: "NY", bio: "Structural engineering for complex NYC projects including DOB filings.", services: ["Structural Design","DOB Filings","Special Inspections"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at NYSED.gov." },
  { name: "Empire State Electric", specialty: "Electrical", licenseNumber: "NYC-45678", licenseState: "NY", rating: "4.60", reviewCount: 134, yearsExperience: 18, projectsCompleted: 220, phone: "(212) 555-0204", email: "service@empireelectric.com", city: "New York", state: "NY", bio: "Licensed electrical contractor for residential and commercial projects.", services: ["Rewiring","Service Upgrades","Condo Electrical"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at NYC.gov/buildings." },
  { name: "Five Boroughs Plumbing", specialty: "Plumbing", licenseNumber: "NYC-56789", licenseState: "NY", rating: "4.50", reviewCount: 87, yearsExperience: 14, projectsCompleted: 160, phone: "(718) 555-0205", email: "jobs@5bplumbing.com", city: "New York", state: "NY", bio: "Licensed plumbing contractor serving all NYC boroughs.", services: ["New Construction","Gas Piping","Boilers"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at NYC.gov/buildings." },
  // LOS ANGELES
  { name: "LA Construction Pros", specialty: "General Contractor", licenseNumber: "CA-LAX-12345", licenseState: "CA", rating: "4.70", reviewCount: 195, yearsExperience: 19, projectsCompleted: 380, phone: "(310) 555-0301", email: "info@laconstruction.com", city: "Los Angeles", state: "CA", bio: "Full-service residential and commercial construction in LA County.", services: ["New Construction","ADUs","Renovations"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  { name: "SoCal Structural", specialty: "Structural Engineering", licenseNumber: "CA-SE-23456", licenseState: "CA", rating: "4.80", reviewCount: 76, yearsExperience: 21, projectsCompleted: 200, phone: "(213) 555-0302", email: "projects@socalstructural.com", city: "Los Angeles", state: "CA", bio: "Structural engineering with seismic design expertise.", services: ["Seismic Design","Retrofitting","Structural Analysis"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at BPELSG.ca.gov." },
  { name: "Pacific Coast Electric", specialty: "Electrical", licenseNumber: "CA-LAX-34567", licenseState: "CA", rating: "4.60", reviewCount: 112, yearsExperience: 13, projectsCompleted: 175, phone: "(323) 555-0303", email: "service@pcelectric.com", city: "Los Angeles", state: "CA", bio: "Licensed electrical contractor for residential and commercial projects.", services: ["Service Upgrades","EV Charging","Solar Integration"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  { name: "Hollywood Hills Builders", specialty: "Luxury Residential", licenseNumber: "CA-LAX-45678", licenseState: "CA", rating: "4.90", reviewCount: 64, yearsExperience: 24, projectsCompleted: 120, phone: "(310) 555-0304", email: "info@hollywoodhillsbuild.com", city: "Los Angeles", state: "CA", bio: "Luxury custom homes in the Hollywood Hills and Beverly Hills.", services: ["Custom Homes","Luxury Renovations","Pools"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  { name: "Valley HVAC Solutions", specialty: "HVAC", licenseNumber: "CA-LAX-56789", licenseState: "CA", rating: "4.50", reviewCount: 98, yearsExperience: 11, projectsCompleted: 140, phone: "(818) 555-0305", email: "schedule@valleyhvac.com", city: "Los Angeles", state: "CA", bio: "HVAC installation and service for residential construction.", services: ["System Design","Installation","Smart Thermostats"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  // CHICAGO
  { name: "Windy City Construction", specialty: "General Contractor", licenseNumber: "CHI-12345", licenseState: "IL", rating: "4.70", reviewCount: 168, yearsExperience: 20, projectsCompleted: 350, phone: "(312) 555-0401", email: "info@windycitybuild.com", city: "Chicago", state: "IL", bio: "Residential and commercial construction throughout Chicago.", services: ["New Construction","Renovations","Historic Preservation"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at Chicago.gov/buildings." },
  { name: "Lakeside Electric", specialty: "Electrical", licenseNumber: "CHI-23456", licenseState: "IL", rating: "4.60", reviewCount: 95, yearsExperience: 15, projectsCompleted: 180, phone: "(773) 555-0402", email: "service@lakesideelectric.com", city: "Chicago", state: "IL", bio: "Licensed electrical contractor for Chicago residential and commercial.", services: ["Service Upgrades","Knob & Tube Replacement","Smart Home Wiring"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at Chicago.gov/buildings." },
  { name: "Chi-Town Plumbing", specialty: "Plumbing", licenseNumber: "CHI-34567", licenseState: "IL", rating: "4.50", reviewCount: 124, yearsExperience: 17, projectsCompleted: 200, phone: "(312) 555-0403", email: "jobs@chitownplumbing.com", city: "Chicago", state: "IL", bio: "Full-service plumbing for new construction and renovations.", services: ["New Construction","Bath Remodels","Water Heaters"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at Chicago.gov/buildings." },
  { name: "Midwest Structural", specialty: "Structural Engineering", licenseNumber: "IL-SE-45678", licenseState: "IL", rating: "4.80", reviewCount: 58, yearsExperience: 23, projectsCompleted: 170, phone: "(312) 555-0404", email: "projects@midweststructural.com", city: "Chicago", state: "IL", bio: "Structural engineering for residential and light commercial.", services: ["Foundation Design","Structural Analysis","Permit Drawings"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at IDFPR.com." },
  { name: "Great Lakes Masonry", specialty: "Masonry", licenseNumber: "CHI-56789", licenseState: "IL", rating: "4.60", reviewCount: 82, yearsExperience: 30, projectsCompleted: 250, phone: "(773) 555-0405", email: "info@greatlakesmasonry.com", city: "Chicago", state: "IL", bio: "Brick, stone, and masonry construction for Chicago homes.", services: ["Brickwork","Stone Facades","Tuckpointing"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at Chicago.gov/buildings." },
  // HOUSTON
  { name: "Houston Home Builders", specialty: "General Contractor", licenseNumber: "TX-HOU-12345", licenseState: "TX", rating: "4.60", reviewCount: 145, yearsExperience: 18, projectsCompleted: 290, phone: "(713) 555-0501", email: "info@houstonhomebuilders.com", city: "Houston", state: "TX", bio: "Custom home builder serving the greater Houston area.", services: ["Custom Homes","Spec Homes","Renovations"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Bayou City Electric", specialty: "Electrical", licenseNumber: "TX-HOU-23456", licenseState: "TX", rating: "4.70", reviewCount: 103, yearsExperience: 14, projectsCompleted: 190, phone: "(713) 555-0502", email: "service@bayoucityelectric.com", city: "Houston", state: "TX", bio: "Licensed electrical contractor for residential construction.", services: ["New Construction","Service Upgrades","Generator Install"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Space City HVAC", specialty: "HVAC", licenseNumber: "TX-HOU-34567", licenseState: "TX", rating: "4.50", reviewCount: 89, yearsExperience: 12, projectsCompleted: 150, phone: "(281) 555-0503", email: "schedule@spacecityhvac.com", city: "Houston", state: "TX", bio: "HVAC design and installation for Houston-area homes.", services: ["Central AC","Heat Pumps","Ductwork"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Gulf Coast Roofing", specialty: "Roofing", licenseNumber: "TX-HOU-45678", licenseState: "TX", rating: "4.80", reviewCount: 167, yearsExperience: 20, projectsCompleted: 310, phone: "(713) 555-0504", email: "info@gulfcoastroofing.com", city: "Houston", state: "TX", bio: "Residential and commercial roofing with storm damage expertise.", services: ["New Roofs","Storm Repair","Metal Roofing"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  { name: "Houston Foundation Repair", specialty: "Foundation", licenseNumber: "TX-HOU-56789", licenseState: "TX", rating: "4.60", reviewCount: 134, yearsExperience: 25, projectsCompleted: 280, phone: "(713) 555-0505", email: "info@houstonfoundation.com", city: "Houston", state: "TX", bio: "Foundation repair and new foundation installation for Houston clay soils.", services: ["Slab Repair","Pier & Beam","Drainage"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at TDLR.texas.gov." },
  // PHOENIX
  { name: "Desert Ridge Builders", specialty: "General Contractor", licenseNumber: "AZ-PHX-12345", licenseState: "AZ", rating: "4.70", reviewCount: 122, yearsExperience: 16, projectsCompleted: 260, phone: "(602) 555-0601", email: "info@desertridgebuilders.com", city: "Phoenix", state: "AZ", bio: "Custom home builder in the Phoenix metro area.", services: ["Custom Homes","Remodels","Outdoor Living"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at ROC.az.gov." },
  { name: "Valley of the Sun HVAC", specialty: "HVAC", licenseNumber: "AZ-PHX-23456", licenseState: "AZ", rating: "4.60", reviewCount: 156, yearsExperience: 19, projectsCompleted: 230, phone: "(480) 555-0602", email: "service@valleysunhvac.com", city: "Phoenix", state: "AZ", bio: "HVAC specialists for extreme Arizona desert climate.", services: ["AC Installation","Ductless Mini-Splits","Energy Efficiency"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at ROC.az.gov." },
  { name: "Sonoran Concrete", specialty: "Concrete", licenseNumber: "AZ-PHX-34567", licenseState: "AZ", rating: "4.50", reviewCount: 88, yearsExperience: 13, projectsCompleted: 170, phone: "(602) 555-0603", email: "bids@sonoranconcrete.com", city: "Phoenix", state: "AZ", bio: "Decorative and structural concrete for desert environments.", services: ["Foundations","Stamped Concrete","Pools"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at ROC.az.gov." },
  { name: "Grand Canyon Electric", specialty: "Electrical", licenseNumber: "AZ-PHX-45678", licenseState: "AZ", rating: "4.70", reviewCount: 94, yearsExperience: 15, projectsCompleted: 185, phone: "(480) 555-0604", email: "service@grandcanyonelectric.com", city: "Phoenix", state: "AZ", bio: "Licensed electrical contractor serving the Phoenix metro.", services: ["New Construction","Solar","EV Charging"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at ROC.az.gov." },
  { name: "Arizona Pool & Spa", specialty: "Pool Builder", licenseNumber: "AZ-PHX-56789", licenseState: "AZ", rating: "4.80", reviewCount: 203, yearsExperience: 22, projectsCompleted: 420, phone: "(602) 555-0605", email: "info@azpoolandspa.com", city: "Phoenix", state: "AZ", bio: "Custom pool and spa construction throughout the Valley.", services: ["Custom Pools","Spas","Pool Remodels"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at ROC.az.gov." },
  // SAN FRANCISCO
  { name: "SF Bay Builders", specialty: "General Contractor", licenseNumber: "CA-SFO-12345", licenseState: "CA", rating: "4.80", reviewCount: 87, yearsExperience: 20, projectsCompleted: 160, phone: "(415) 555-0701", email: "info@sfbaybuilders.com", city: "San Francisco", state: "CA", bio: "High-end residential construction in San Francisco.", services: ["Renovations","Additions","Seismic Retrofit"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  { name: "Golden Gate Structural", specialty: "Structural Engineering", licenseNumber: "CA-SE-23456", licenseState: "CA", rating: "4.90", reviewCount: 52, yearsExperience: 28, projectsCompleted: 140, phone: "(415) 555-0702", email: "projects@goldengatestructural.com", city: "San Francisco", state: "CA", bio: "Structural engineering with seismic and soft-story expertise.", services: ["Seismic Retrofit","Soft-Story","New Design"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at BPELSG.ca.gov." },
  { name: "Fog City Electric", specialty: "Electrical", licenseNumber: "CA-SFO-34567", licenseState: "CA", rating: "4.60", reviewCount: 73, yearsExperience: 16, projectsCompleted: 130, phone: "(415) 555-0703", email: "service@fogcityelectric.com", city: "San Francisco", state: "CA", bio: "Licensed electrical contractor for SF residential.", services: ["Knob & Tube Removal","Service Upgrades","EV Charging"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  { name: "Pacific Heights Renovations", specialty: "Luxury Renovation", licenseNumber: "CA-SFO-45678", licenseState: "CA", rating: "4.90", reviewCount: 41, yearsExperience: 22, projectsCompleted: 85, phone: "(415) 555-0704", email: "info@pacificheightsreno.com", city: "San Francisco", state: "CA", bio: "Luxury renovations in Pacific Heights, Nob Hill, and Presidio Heights.", services: ["Whole House Reno","Kitchen & Bath","Historic Preservation"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify license at CSLB.ca.gov." },
  { name: "Bay Area Green Building", specialty: "Green Building", licenseNumber: "CA-SFO-56789", licenseState: "CA", rating: "4.70", reviewCount: 36, yearsExperience: 14, projectsCompleted: 60, phone: "(415) 555-0705", email: "info@bayareagreenbuild.com", city: "San Francisco", state: "CA", bio: "Green building with LEED Platinum and Net Zero focus.", services: ["LEED Homes","Net Zero","Passive House"], isVerified: true, disclaimer: "Not endorsed by Landrealm. Verify certifications at USGBC.org." },
];

console.log(`Inserting ${contractorData.length} contractors...`);
await db.insert(schema.contractors).values(contractorData);
console.log(`  Contractors inserted.\n`);

// ──────────────────────────────────────────
// STEP 3: OVERLAY LAYERS
// ──────────────────────────────────────────

const overlayData = [
  { name: "historic_landmark", type: "historic", displayName: "Historic Landmark District", description: "Properties within designated historic districts require HAHC review for exterior alterations.", jurisdiction: "Austin, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { districtCount: 7, contact: "512-974-2727" }, isActive: true },
  { name: "floodplain_100yr", type: "environmental", displayName: "100-Year Floodplain", description: "FEMA 100-year floodplain. Buildings require elevation or flood-proofing.", jurisdiction: "Austin, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { source: "FEMA", effectiveDate: "2024-03-01" }, isActive: true },
  { name: "airport_zone", type: "noise", displayName: "ABIA Airport Zone", description: "ABIA airport overlay. Height restrictions and sound insulation requirements apply.", jurisdiction: "Austin, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { airport: "Austin-Bergstrom International" }, isActive: true },
  { name: "waterfront", type: "environmental", displayName: "Lake Austin Waterfront", description: "Critical Water Quality Zone. Impervious cover limits and buffer requirements.", jurisdiction: "Austin, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { bufferWidth: 150 }, isActive: true },
  { name: "transit_corridor", type: "transit", displayName: "Transit Corridor", description: "Transit-oriented development corridor with enhanced density and reduced parking.", jurisdiction: "Austin, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { transitLine: "MetroRapid" }, isActive: true },
  // NYC
  { name: "historic_district", type: "historic", displayName: "Historic District (LPC)", description: "NYC Landmarks Preservation Commission district. All exterior work requires LPC permits.", jurisdiction: "New York, NY", polygonData: { type: "FeatureCollection", features: [] }, metadata: { districtCount: 149, contact: "212-669-7700" }, isActive: true },
  { name: "coastal_zone", type: "environmental", displayName: "Special Coastal Risk District", description: "Post-Sandy coastal resiliency zone. Elevation and flood-proofing requirements.", jurisdiction: "New York, NY", polygonData: { type: "FeatureCollection", features: [] }, metadata: { source: "NYC DCP", effectiveDate: "2021-01-01" }, isActive: true },
  { name: "inclusionary_housing", type: "affordable", displayName: "Inclusionary Housing Designated Area", description: "Mandatory inclusionary housing zone. 25-30% of units must be affordable.", jurisdiction: "New York, NY", polygonData: { type: "FeatureCollection", features: [] }, metadata: { mfiRange: "80-130%" }, isActive: true },
  { name: "transit_zone", type: "transit", displayName: "Transit Zone (Parking Waiver)", description: "Reduced or waived parking requirements within 1/2 mile of subway/rail.", jurisdiction: "New York, NY", polygonData: { type: "FeatureCollection", features: [] }, metadata: { transitModes: ["Subway","LIRR","Metro-North"] }, isActive: true },
  { name: "landmark_individual", type: "historic", displayName: "Individual Landmark", description: "Individual NYC landmark properties. Any alteration requires LPC approval.", jurisdiction: "New York, NY", polygonData: { type: "FeatureCollection", features: [] }, metadata: { landmarkCount: 1200 }, isActive: true },
  // LA
  { name: "historic_preservation", type: "historic", displayName: "Historic Preservation Overlay Zone", description: "HPOZ district. Design review required for exterior changes.", jurisdiction: "Los Angeles, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { hpozCount: 35 }, isActive: true },
  { name: "fault_zone", type: "geologic", displayName: "Earthquake Fault Zone", description: "Alquist-Priolo Earthquake Fault Zone. Setback from known active faults required.", jurisdiction: "Los Angeles, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { source: "CGS", setback: 50 }, isActive: true },
  { name: "fire_hazard", type: "safety", displayName: "Very High Fire Hazard Severity Zone", description: "Cal Fire designated high fire zone. Fire-resistant construction required.", jurisdiction: "Los Angeles, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { calFireZone: true, requirements: ["Class A roofing","Defensible space"] }, isActive: true },
  { name: "coastal_zone_la", type: "environmental", displayName: "Coastal Zone", description: "California Coastal Commission jurisdiction. Development permit required.", jurisdiction: "Los Angeles, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { cccJurisdiction: true }, isActive: true },
  { name: "transit_priority", type: "transit", displayName: "Transit Priority Area", description: "TOC density bonus area near major transit. Parking reductions available.", jurisdiction: "Los Angeles, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { tocTiers: [1,2,3,4] }, isActive: true },
  // CHICAGO
  { name: "landmark_district", type: "historic", displayName: "Landmark District", description: "Chicago Landmark District. Commission on Chicago Landmarks review required.", jurisdiction: "Chicago, IL", polygonData: { type: "FeatureCollection", features: [] }, metadata: { districtCount: 60 }, isActive: true },
  { name: "floodway", type: "environmental", displayName: "Floodway", description: "FEMA regulated floodway. Construction severely restricted.", jurisdiction: "Chicago, IL", polygonData: { type: "FeatureCollection", features: [] }, metadata: { source: "FEMA" }, isActive: true },
  { name: "tif_district", type: "economic", displayName: "Tax Increment Financing District", description: "TIF district. Additional financing mechanisms available for development.", jurisdiction: "Chicago, IL", polygonData: { type: "FeatureCollection", features: [] }, metadata: { tifCount: 120 }, isActive: true },
  { name: "planned_development", type: "zoning", displayName: "Planned Development District", description: "PD district with site-specific zoning. Custom zoning package required.", jurisdiction: "Chicago, IL", polygonData: { type: "FeatureCollection", features: [] }, metadata: { requiresAldermanApproval: true }, isActive: true },
  { name: "neighborhood_conservation", type: "historic", displayName: "Neighborhood Conservation District", description: "NCD with design guidelines. Administrative review for exterior changes.", jurisdiction: "Chicago, IL", polygonData: { type: "FeatureCollection", features: [] }, metadata: { ncdCount: 10 }, isActive: true },
  // HOUSTON
  { name: "historic_district_hou", type: "historic", displayName: "Historic District", description: "Houston historic district. HAHC Certificate of Appropriateness required.", jurisdiction: "Houston, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { districtCount: 22 }, isActive: true },
  { name: "floodplain_hou", type: "environmental", displayName: "Floodplain (Post-Harvey)", description: "Updated floodplain maps post-Hurricane Harvey. Elevation required.", jurisdiction: "Houston, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { source: "FEMA/HCFCD", effectiveDate: "2023-01-01" }, isActive: true },
  { name: "municipal_utility", type: "utility", displayName: "Municipal Utility District", description: "MUD district. Special water/sewer infrastructure requirements.", jurisdiction: "Houston, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { mudCount: 700 }, isActive: true },
  { name: "buffer_zone", type: "environmental", displayName: "Rail/Utility Buffer", description: "Buffer zone adjacent to railroads and major utilities. Setback requirements.", jurisdiction: "Houston, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { bufferWidth: 25 }, isActive: true },
  { name: "urban_corridor", type: "transit", displayName: "Urban Corridors", description: "Urban corridor with enhanced standards. Form-based code applies.", jurisdiction: "Houston, TX", polygonData: { type: "FeatureCollection", features: [] }, metadata: { corridorCount: 16 }, isActive: true },
  // PHOENIX
  { name: "historic_district_phx", type: "historic", displayName: "Historic District", description: "Phoenix historic district. Historic Preservation Commission review required.", jurisdiction: "Phoenix, AZ", polygonData: { type: "FeatureCollection", features: [] }, metadata: { districtCount: 35 }, isActive: true },
  { name: "floodplain_phx", type: "environmental", displayName: "Regulatory Floodplain", description: "FEMA regulatory floodplain. Elevation or flood-proofing required.", jurisdiction: "Phoenix, AZ", polygonData: { type: "FeatureCollection", features: [] }, metadata: { source: "FEMA" }, isActive: true },
  { name: "desert_wash", type: "environmental", displayName: "Desert Wash / Riparian", description: "Protected desert wash. 75-foot buffer with native vegetation requirements.", jurisdiction: "Phoenix, AZ", polygonData: { type: "FeatureCollection", features: [] }, metadata: { bufferWidth: 75, vegetationRequired: true }, isActive: true },
  { name: "light_rail", type: "transit", displayName: "Light Rail Transit Corridor", description: "Valley Metro Rail corridor. Transit-oriented development standards.", jurisdiction: "Phoenix, AZ", polygonData: { type: "FeatureCollection", features: [] }, metadata: { stations: 41 }, isActive: true },
  { name: "airport_envelope", type: "noise", displayName: "Sky Harbor Airport Envelope", description: "Sky Harbor height limitation envelope. Height restrictions apply.", jurisdiction: "Phoenix, AZ", polygonData: { type: "FeatureCollection", features: [] }, metadata: { airport: "Sky Harbor International" }, isActive: true },
  // SAN FRANCISCO
  { name: "historic_district_sf", type: "historic", displayName: "Historic District", description: "SF Historic District. Historic Preservation Commission review required.", jurisdiction: "San Francisco, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { districtCount: 18 }, isActive: true },
  { name: "liquefaction", type: "geologic", displayName: "Liquefaction Zone", description: "Seismic liquefaction susceptibility zone. Geotechnical investigation required.", jurisdiction: "San Francisco, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { requiresGeotech: true }, isActive: true },
  { name: "soft_story", type: "seismic", displayName: "Mandatory Soft-Story Program", description: "Mandatory seismic retrofit required for wood-frame soft-story buildings.", jurisdiction: "San Francisco, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { deadline: "2024-09-15", program: "Mandatory" }, isActive: true },
  { name: "coastal_zone_sf", type: "environmental", displayName: "Coastal Zone", description: "California Coastal Commission jurisdiction. Coastal Development Permit required.", jurisdiction: "San Francisco, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { cccJurisdiction: true }, isActive: true },
  { name: "planned_unit", type: "zoning", displayName: "Planned Unit Development", description: "PUD with negotiated development standards. Approval by Planning Commission.", jurisdiction: "San Francisco, CA", polygonData: { type: "FeatureCollection", features: [] }, metadata: { requiresPlanningCommission: true }, isActive: true },
];

console.log(`Inserting ${overlayData.length} overlay layers...`);
await db.insert(schema.overlayLayers).values(overlayData);
console.log(`  Overlays inserted.\n`);

// ──────────────────────────────────────────
// STEP 4: REGULATORY ALERTS
// ──────────────────────────────────────────

const alertData = [
  { jurisdiction: "Austin, TX", alertType: "zoning", severity: "high", title: "Compatibility Standards Expanded (CodeNEXT)", summary: "New compatibility standards now apply within 300ft of single-family zoning. Height stepbacks and FAR reductions required.", fullText: "Effective January 2025, the expanded compatibility standards apply to all properties within 300 feet of single-family zoning districts. Projects must incorporate graduated height stepbacks: 50ft at property line, increasing to full height at 150ft. FAR limited to 0.75 within 150ft of SF districts.", effectiveDate: new Date("2025-01-01"), source: "City of Austin Development Services", sourceUrl: "https://www.austintexas.gov/development-services" },
  { jurisdiction: "Austin, TX", alertType: "environmental", severity: "medium", title: "Tree Ordinance Update — 2024", summary: "Protected tree size threshold reduced from 24 inches to 19 inches DBH. Replacement required at 2:1 ratio.", fullText: "The City of Austin updated its tree ordinance. Protected tree threshold is now 19 inches DBH. Trees within the critical root zone may not be removed without replacement at a 2-inch-for-1-inch ratio.", effectiveDate: new Date("2024-06-01"), source: "Austin Code Department" },
  { jurisdiction: "Austin, TX", alertType: "permit", severity: "low", title: "Online Portal — New Submittal Requirements", summary: "All residential plan review submittals must now use the new ACA portal. Paper submittals no longer accepted.", effectiveDate: new Date("2025-03-01"), source: "Austin Development Services" },
  // NYC
  { jurisdiction: "New York, NY", alertType: "zoning", severity: "high", title: "City of Yes for Housing Opportunity", summary: "Major zoning text amendment allows ADUs, office-to-residential conversion, and eliminates parking mandates near transit.", fullText: "The City of Yes for Housing Opportunity adopted December 2024 allows accessory dwelling units citywide, removes parking mandates within 1/2 mile of transit, and streamlines office-to-residential conversions.", effectiveDate: new Date("2024-12-05"), source: "NYC Department of City Planning", sourceUrl: "https://www.nyc.gov/site/planning/plans/city-of-yes.page" },
  { jurisdiction: "New York, NY", alertType: "building", severity: "high", title: "Local Law 97 — Carbon Emission Limits", summary: "Buildings over 25,000 sqft must meet carbon emission caps starting 2025. Penalties for non-compliance.", fullText: "Local Law 97 requires buildings over 25,000 sqft to meet annual greenhouse gas emission limits starting 2025. Non-compliant buildings face penalties of $268 per ton of CO2e over limit.", effectiveDate: new Date("2025-01-01"), source: "NYC DOB" },
  { jurisdiction: "New York, NY", alertType: "permit", severity: "medium", title: "DOB NOW: All BIS Jobs Migrated", summary: "All remaining BIS jobs have been migrated to DOB NOW. BIS is no longer accessible.", effectiveDate: new Date("2025-01-15"), source: "NYC DOB" },
  // LA
  { jurisdiction: "Los Angeles, CA", alertType: "zoning", severity: "high", title: "Mansionization Ordinance Update", summary: "Updated R-1 mansionization rules reduce maximum floor area and increase open space requirements.", fullText: "The updated mansionization ordinance for R-1 zones reduces the maximum floor area ratio and increases rear yard and open space requirements. Grading limited to 2,000 cubic yards without discretionary review.", effectiveDate: new Date("2024-09-01"), source: "LA City Planning" },
  { jurisdiction: "Los Angeles, CA", alertType: "environmental", severity: "medium", title: "Water Conservation Ordinance — 2025", summary: "New water conservation standards for landscaping. Max 25% turf for new residential.", fullText: "The updated water conservation ordinance limits turf to 25% of landscaped area for new residential projects. Drought-tolerant and California native plants required for the remaining 75%.", effectiveDate: new Date("2025-01-01"), source: "LADBS / LADWP" },
  { jurisdiction: "Los Angeles, CA", alertType: "seismic", severity: "high", title: "Mandatory Seismic Retrofit — Wood Soft-Story", summary: "Deadline for soft-story retrofit compliance extended to 2027. Applies to ~12,000 buildings.", fullText: "The mandatory wood-frame soft-story retrofit program deadline has been extended to 2027. Applies to approximately 12,000 buildings identified by the city. Retrofit includes shear walls and moment frames.", effectiveDate: new Date("2027-12-31"), source: "LA Emergency Management Department" },
  // CHICAGO
  { jurisdiction: "Chicago, IL", alertType: "zoning", severity: "high", title: "Affordable Requirements Ordinance (ARO) Expansion", summary: "ARO expanded to all zoning districts citywide. 10% affordable required or in-lieu fee.", fullText: "The Affordable Requirements Ordinance has been expanded citywide. All residential developments with 10+ units must provide 10% affordable units on-site or pay an in-lieu fee of $175,000 per unit.", effectiveDate: new Date("2025-01-01"), source: "Chicago Department of Planning and Development" },
  { jurisdiction: "Chicago, IL", alertType: "historic", severity: "medium", title: "Demolition Delay Ordinance Extended", summary: "Demolition delay for contributing structures in historic districts extended from 90 to 180 days.", fullText: "The demolition delay ordinance has been extended from 90 days to 180 days for contributing structures within Chicago Landmark Districts.", effectiveDate: new Date("2024-11-01"), source: "Commission on Chicago Landmarks" },
  { jurisdiction: "Chicago, IL", alertType: "building", severity: "high", title: "Energy Benchmarking — Phase 2 Expansion", summary: "Energy benchmarking now required for all buildings over 25,000 sqft. Annual reporting mandatory.", effectiveDate: new Date("2025-06-01"), source: "Chicago Department of Buildings" },
  // HOUSTON
  { jurisdiction: "Houston, TX", alertType: "development", severity: "high", title: "Chapter 42 Minimum Lot Size Update", summary: "Minimum lot size for new residential subdivisions reduced from 3,500 to 1,400 sqft in certain areas.", fullText: "The Chapter 42 minimum lot size requirement has been reduced from 3,500 sqft to 1,400 sqft in areas within Loop 610 and along major transit corridors. This enables higher-density development.", effectiveDate: new Date("2025-01-01"), source: "Houston Planning and Development" },
  { jurisdiction: "Houston, TX", alertType: "environmental", severity: "medium", title: "Updated Floodplain Maps — HCFCD", summary: "New 2024 floodplain maps effective. Some previously unmapped areas now in 100-year floodplain.", fullText: "Harris County Flood Control District released updated floodplain maps effective 2024. Some properties previously outside the 100-year floodplain are now included. Elevation certificates required for new construction.", effectiveDate: new Date("2024-10-01"), source: "HCFCD" },
  { jurisdiction: "Houston, TX", alertType: "building", severity: "low", title: "Residential Energy Code Update to 2021 IECC", summary: "Houston adopted 2021 IECC for residential construction. Higher insulation and air sealing requirements.", effectiveDate: new Date("2025-01-01"), source: "Houston Public Works" },
  // PHOENIX
  { jurisdiction: "Phoenix, AZ", alertType: "zoning", severity: "high", title: "Phoenix General Plan 2050 — Proposed Zoning Changes", summary: "Proposed update to General Plan 2050 includes new transit-oriented zoning categories and density bonuses.", fullText: "The Phoenix General Plan 2050 update proposes new TOD zoning categories along light rail and bus rapid transit corridors. Density bonuses of up to 200% FAR proposed within 1/2 mile of transit stations.", effectiveDate: new Date("2026-01-01"), source: "Phoenix Planning & Development" },
  { jurisdiction: "Phoenix, AZ", alertType: "environmental", severity: "medium", title: "Heat Ready Program — New Requirements", summary: "New Heat Ready requirements for outdoor spaces. Shade coverage and cool surface materials required.", fullText: "The Heat Ready program now requires minimum shade coverage in outdoor common areas and cool/reflective surface materials for all new multi-family and commercial projects.", effectiveDate: new Date("2025-05-01"), source: "City of Phoenix Office of Heat Response" },
  { jurisdiction: "Phoenix, AZ", alertType: "water", severity: "high", title: "Colorado River Shortage — Stage 2", summary: "CAP Stage 2 shortage declared. Restrictions on new residential lot sizes over 8,000 sqft.", fullText: "The Central Arizona Project has declared a Stage 2 shortage on the Colorado River. New residential lots over 8,000 sqft face additional landscape water restrictions.", effectiveDate: new Date("2025-01-01"), source: "Arizona Department of Water Resources" },
  // SAN FRANCISCO
  { jurisdiction: "San Francisco, CA", alertType: "housing", severity: "high", title: "Housing Element 2023 — Density Bonus Expansion", summary: "State-certified Housing Element mandates increased density. Height district changes along transit corridors.", fullText: "The 2023 Housing Element has been state-certified. Density bonuses of up to 50% are now available citywide for projects including affordable housing. Height districts along major transit corridors have been increased.", effectiveDate: new Date("2024-01-01"), source: "San Francisco Planning Department" },
  { jurisdiction: "San Francisco, CA", alertType: "seismic", severity: "high", title: "Soft-Story Retrofit — Final Deadline Extended", summary: "Final deadline for mandatory soft-story retrofit extended to September 2024.", fullText: "The final deadline for mandatory soft-story retrofit has been extended to September 15, 2024. Approximately 3,000 buildings still not compliant. Penalties of $100/day for non-compliance after deadline.", effectiveDate: new Date("2024-09-15"), source: "SF DBI" },
  { jurisdiction: "San Francisco, CA", alertType: "environmental", severity: "medium", title: "Green Landscaping Ordinance Update", summary: "Updated green landscaping requirements. 30% of site must be pervious with native/drought-tolerant plants.", fullText: "The updated Green Landscaping Ordinance requires 30% of the total site area to be pervious surface with native or drought-tolerant plantings. Rain gardens and bio-swales encouraged.", effectiveDate: new Date("2025-01-01"), source: "SF Planning Department" },
];

console.log(`Inserting ${alertData.length} regulatory alerts...`);
await db.insert(schema.regulatoryAlerts).values(alertData);
console.log(`  Alerts inserted.\n`);

console.log('');
console.log('========================================');
console.log('  NATIONWIDE SEED COMPLETE');
console.log('========================================');
console.log(`  Cities covered: 7 major metros`);
console.log(`  Zoning rules: ${zoningRulesData.length}`);
console.log(`  Contractors: ${contractorData.length}`);
console.log(`  Overlay layers: ${overlayData.length}`);
console.log(`  Regulatory alerts: ${alertData.length}`);
console.log('========================================');

await client.end();
console.log('\nDatabase connection closed.');
